setup.py
=> Update setup.py install requirements

.github/CODEOWNERS
Auto-request reviews from @igboyes and @jakeale.
=> Add .github and CODEOWNERS file

virtool_cli/isolate.py, virtool_cli/utils.py
- Renamed and split functions up for better code clarity
- Changed ids to have separate tables for what is considered unique depending on whether it's an isolate id or a sequence id - i.e. there is no restrictions on a sequence having the same id as an isolate
- Added docstrings and typings
=> Update how uniqueness of ids are determined, docstrings, typings

tests/test_build.py, virtool_cli/isolate.py, virtool_cli/utils.py
- Resolves #20 and resolves #21
- Resolves #22
=> Add more informative logging, KeyboardInterrupt handling

virtool_cli/isolate.py, virtool_cli/taxid.py
=> Improve code clarity, add types

virtool_cli/isolate.py, virtool_cli/taxid.py, virtool_cli/utils.py
=> Add utils function to gather NCBI authentication details and REQUEST_INTERVAL

.github/workflows/virtool-cli.yml
=> Fix Github actions

virtool_cli/taxid.py
- Update logging to be similar to that of isolate (closes #30)
- Update docstrings to use Sphinx format
- Update some types
=> Update taxid subcommand logging 

tests/test_taxid.py, virtool_cli/divide.py, virtool_cli/isolate.py, virtool_cli/repair.py, virtool_cli/run.py, virtool_cli/utils.py
=> Add repair subcommand

virtool_cli/build.py, virtool_cli/divide.py, virtool_cli/isolate.py, virtool_cli/repair.py, virtool_cli/run.py, virtool_cli/taxid.py, virtool_cli/utils.py
- resolves #41
- fixes some docstring formats
=> Use pathlib objects instead of strings

tests/conftest.py, tests/test_curate_vfam.py, virtool_cli/vfam.py, virtool_cli/vfam_collapse.py, virtool_cli/vfam_curate.py, virtool_cli/vfam_filter.py, virtool_cli/vfam_markov.py, virtool_cli/vfam_msa.py, virtool_cli/vfam_polyprotein.py
* Add generators for all file i/o when not using SeqIO to limit memory usage
=> Add generators to VFam modules

tests/test_annotation_vfam.py, virtool_cli/run.py, virtool_cli/vfam.py, virtool_cli/vfam_annotation.py, virtool_cli/vfam_collapse.py, virtool_cli/vfam_console.py, virtool_cli/vfam_curate.py, virtool_cli/vfam_filter.py, virtool_cli/vfam_markov.py, virtool_cli/vfam_msa.py, virtool_cli/vfam_polyprotein.py
* Add console logging using rich to VFam workflow
=> Improve console logging for VFam click command

tests/test_curate_vfam.py, virtool_cli/vfam_annotation.py, virtool_cli/vfam_curate.py
* Add error message for case where NCBI doesn't find record
* Add message containing number of families and genus found
=> Update logging for gathering taxonomic information

.github/workflows/publish.yml, pyproject.toml
* Use generic version in `pyproject.toml`.
* Use GitHub ref to set version using `poetry version`.
* This is a dry run for now.
=> Add dry PyPI publish action

.github/workflows/ci.yml, .github/workflows/publish.yml
* Release on push to `master` branch. Publish to Dockerhub on release publication.
=> Update GitHub actions for semantic-release

.github/workflows/ci.yml
Add 'needs: test' to release job to ensure release stops if test fail
=> Use github.event_name instead of github.event.name

tests/test_merge_refs.py, virtool_cli/merge_refs.py, virtool_cli/run.py
write CSV file for isolates with unknown source names or source types.
Update tests.
=> Add --format-unknown-isolates option

.deepsource.toml
Update Deepsource config to:
* Point to test files correctly.
* Scan for secrets.
=> ci: update .deepsource.toml

tests/test_ncbi_client.py, virtool_cli/ncbi/client.py
Async will be handled strictly at the function level in the future.
=> Remove all async functionality from NCBIClient

tests/test_repo.py, virtool_cli/ref/events.py, virtool_cli/ref/repo.py, virtool_cli/ref/resources.py
Abbreviation is the wrong word, so let's correct it.
=> Change `abbreviation` to `acronym`

tests/test_ncbi_model.py, virtool_cli/ncbi/client.py, virtool_cli/ncbi/model.py
- NCBIGenbank validator now rejects sequence data with bad letters
- Test only accepts errors on the `sequence` field
- Downgraded validation failure from an error log to a debug log
=> NCBIGenbank modifications

tests/conftest.py, tests/test_group_records.py, tests/test_ncbi_cache.py, tests/test_ncbi_client.py, tests/test_ncbi_model.py, tests/test_utils_reference.py, tests/test_utils_storage.py
* Remove fixtures with roughly duplicate functionality.
* Rename some fixtures for consistency and accuracy.
* Add typing.
* Some `ruff` auto-formatting got into these changes.
=> test: consolidate fixtures

virtool_cli/ref/repo.py
- Refactor `./src` write and load into `EventStore`, accessed through `EventSourcedRepo._event_store`
=> Refactor lower-level `EventSourcedRepo` functionality into `EventStore`
